### ISSUE TITLE
Inline JS in Nuxt.js project

### ISSUE THREAD

**Issue by Grawl** [ai/webp-in-css#2]
I work on a project powered by [Nuxt](http://nuxtjs.org) and want to use this plugin with it. The only problem I faced is inlining JS into `<head>`. Solution I [found](https://github.com/nuxt/nuxt.js/issues/2230) is following:

```js
// nuxt.config.js
const webpInCss = fs.readFileSync(require.resolve('webp-in-css'), { encoding: 'utf-8' })
module.exports = {
	head: {
		// …
		script: [
			{ innerHTML: webpInCss },
		],
		__dangerouslyDisableSanitizers: ['script'],
	},
}
```

[`vue-meta`](https://github.com/nuxt/vue-meta) has `__dangerouslyDisableSanitizersByTagID` to disable attribute into selected elements, but it cannot select `innerHTML` as it not an attribute.

```js
	head: {
		// …
		script: [
			{ vmid: 'webp-in-css', innerHTML: webp },
		],
		__dangerouslyDisableSanitizersByTagID: {
			'webp-in-css': 'innerHTML', // this will not work
		},
	},
```

**Comment by ai** [comment]
Do you want to send PR with docs for Nuxt?

**Comment by Grawl** [comment]
I think resolved issue is enough
