### ISSUE TITLE
Error in gulp build

### ISSUE THREAD

**Issue by nullorone** [ai/webp-in-css#3]
I tried to use the plugin in the gulp test build, but I get an error.

![1](https://user-images.githubusercontent.com/35527172/55224153-f1c28900-5220-11e9-8dfc-431857653306.png)

gulp 4.0 version
```
gulp.task("css", function() {
  return gulp
    .src("source/css/style.css")
    .pipe(sourcemaps.init())
    .pipe(postcss([
      webpBg(),
      autoprefixer({
        grid: "autoplace"
      }),
      postcssNormalize({ forceImport: true })
    ]))
    .pipe(csso())
    .pipe(sourcemaps.write())
    .pipe(rename("style.min.css"))
    .pipe(gulp.dest("build/css"))
    .pipe(server.stream());
});
```
My repo with test build - [click](https://github.com/nullorone/test-webp-bg)

How to avoid this error and correctly use the plugin in gulp builds?

**Comment by ai** [comment]
```diff
- var webpBg = require("webp-in-css");
+ var webpBg = require("webp-in-css/plugin");
```
