### ISSUE TITLE
Cannot read properties of null (reading 'classList')

### ISSUE THREAD

**Issue by naxxateux** [ai/webp-in-css#43]
Hi!

I've updated plugin to 0.7.0 version. And when I'm putting it to `head` I'm getting this error: `Cannot read properties of null (reading 'classList')` on `document.body.classList.remove('no-js')`. Should I place script in `body`?

**Comment by ai** [comment]
Very strange. We didn’t change the `polyfill.js` in 0.7 https://github.com/ai/webp-in-css/compare/0.6.0...main

Can yu show the HTML template and `polyfill.js` before the update to 0.7?

**Comment by naxxateux** [comment]
I'm updating from 0.5.1. So from the version without `no-js` support I guess.

**Comment by naxxateux** [comment]
So it is obligatory to add this class to `body` while using polyfill?

**Comment by ai** [comment]
Yeap, let’s try to move it after `<body>`.

Can you send PR to docs?

**Comment by naxxateux** [comment]
Ok. I'll send PR.

**Comment by ai** [comment]
Fixed 72a24ab
