### ISSUE TITLE
Rename standard require path

### ISSUE THREAD

**Issue by dx1ded** [ai/webp-in-css#44]
Hello! I tried to use this plugin but it doens't work for me. I have a generator (in webpack loader) which requires images with specific syntax like `image.jpg?as=webp` and it gives me `image.webp` file. This plugin basically uses `image.webp` as response to `image.jpg` (for example). How can i change it to "image.jpg?as=webp" (instead of image.webp)? Thanks <3

**Comment by ai** [comment]
You need to define `rename` option for this plugin to set a custom path for WebP image

```js
  require('webp-in-css/plugin')({
    rename: url => url.replace('\.jpg', '.jpg?as=webp')
  })
```

**Comment by dx1ded** [comment]
@ai, very strange but it gives me this:

![image](https://user-images.githubusercontent.com/45831463/147422348-8effd832-a53d-409e-bf18-c76db5932fca.png)

(There's what i typed)

![image](https://user-images.githubusercontent.com/45831463/147422357-190d6869-308b-424c-9647-7af99c6da32e.png)

**Comment by ai** [comment]
You also need to define `check` option to ignore URLs wth `as=webp`

**Comment by dx1ded** [comment]
Yeah, it works! Thanks! <33333

**Comment by ai** [comment]
Can you share your options? I will improve docs to help other developers.

**Comment by dx1ded** [comment]
Sure, here it is:

```
module.exports = {
  plugins: [
    require("webp-in-css/plugin")({
      modules: true,
      check: (declaration) => declaration.value.includes("as=webp"),
      rename: (url) => url.replace(".jpg", ".jpg?as=webp")
    }),
    require("autoprefixer")({ grid: "autoplace" }),
    require("cssnano")
  ]
}
```

**Comment by dx1ded** [comment]
Oh, i'm sorry, i was hurried. Probably it works but i don't know how to field regular expression. It tried something like this but it ignores `?as=webp` at all

![image](https://user-images.githubusercontent.com/45831463/147422763-5454dd24-f311-4989-8e3f-b0eab389472a.png)

**Comment by ai** [comment]
> It tried something like this but it ignores ?as=webp at all

Show input, output and expected output examples

**Comment by dx1ded** [comment]
Input:

![image](https://user-images.githubusercontent.com/45831463/147422833-c730c3cb-7eec-4856-86ba-c6e3583e3ac4.png)

Output:

![image](https://user-images.githubusercontent.com/45831463/147422846-fcbfb8e3-23a6-470b-8e6a-f477603ddf96.png)

I expect that this plugin will add additional class like `body.webp { background-image *.webp `}

**Comment by ai** [comment]
Got it. In `check` you need to do opposite thing. You need to find `jpg` *without* `as=webp`.

**Comment by ai** [comment]
Something like:

```js
  check: decl => /\.jpg/.test(decl.value) && !decl.value.includes("as=webp"),
  rename: url => url.replace(".jpg", ".jpg?as=webp")
```

**Comment by dx1ded** [comment]
Yeah! It absolutely works. Thanks u twice <3
