### ISSUE TITLE
The omission of the fourth step from the manual

### ISSUE THREAD

**Issue by mikhin** [ai/webp-in-css#46]
Hi! It seems that fourth step could be omitted from the manual because installing of «webp-in-css» has been already mentioned earlier, in the first step:

**Step 1:** Install tool:

```sh
npm install --save-dev postcss webp-in-css
```

**Step 4:** install `webp-in-css`. For npm use:

```sh
npm install --save-dev webp-in-css
```

What do you think? If needed, I could help with a pull request.

**Comment by ai** [comment]
Thanks! Can you send PR to save your name in the project ’s history.

**Comment by ai** [comment]
Done https://github.com/ai/webp-in-css/commit/f24db96437352cdf67de1709d9300476e2d58801
