### ISSUE TITLE
Offer to change body.webp to html.webp

### ISSUE THREAD

**Issue by Rammfall** [ai/webp-in-css#8]
Hello.
I faced the situation, when I needed to use selector html[lang='*']. In output I got body.webp html[lang='en'].

I think it can be useful to change it on html.webp

**Comment by ai** [comment]
I am not sure that `html.webp` will fix the problem. PostCSS plugin will generate `html.webp html[lang=en]` which still doesn’t wotk.

Maybe we should change https://github.com/ai/webp-in-css/blob/master/plugin.js#L14 and add special logic for `html…` selectors? Do you want to send PR?

**Comment by Rammfall** [comment]
Yes, I'll add this logic

**Comment by Rammfall** [comment]
https://github.com/ai/webp-in-css/pull/9

**Comment by ai** [comment]
I decided to continue using `body` (just insert it after `html`) because using `html` will increase JS size

**Comment by ai** [comment]
Released in 0.1.1
